language: java

install: mvn -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn -Dmaven.compiler.source=6 -Dmaven.compiler.source=6 verify

jdk:
  - oraclejdk7
#  - openjdk8

#branches:
# only:
# - master

notifications:
  email:
    - bernd-2013@eckenfels.net
