language: java

install: mvn -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn -X verify

jdk:
  - oraclejdk7
  - openjdk7
  - openjd8
  - oraclejdk6

#branches:
# only:
# - master

notifications:
  email:
    - bernd-2013@eckenfels.net
