language: java

install: mvn -q clean

# clean / compile - test - package - verify - install - deploy / site
script: mvn verify

jdk:
  - oraclejdk7

#branches:
# only:
# - master

notifications:
  email:
    - bernd-2013@eckenfels.net
