language: java

install: mvn -B -q clean

jdk:
  - oraclejdk6
  - openjdk7

env:
  matrix:
    - VER=6
    - VER=7

matrix:
  include:
    - jdk: oraclejdk6
      env: VER=6
    - jdk: openjdk7
      env: VER=7


# clean / compile - test - package - verify - install - deploy / site
script: mvn -B -X -Dmaven.compiler.source=${VER} -Dmaven.compiler.target=${VER} verify


#branches:
# only:
# - master

notifications:
  email:
    - bernd-2013@eckenfels.net
